### ISSUE TITLE
Incorrect reference file format for assignSpecies.

### ISSUE THREAD

**Issue by domenico-simone** [fkeck/diatbarcode#2]
Hi,

when I run

```r
spe_fas <- diatbarcode::download_diatbarcode(flavor = "rbcl312_dada2_spe")
exact_sp <- assignSpecies(seqtab.nochim, spe_fas$path)
```

I get this error:

```
Error in assignSpecies(seqtab.nochim, spe_fas$path) : 
  Incorrect reference file format for assignSpecies.
```

While with 

```r
spe_fas <- diatbarcode::download_diatbarcode(flavor = "rbcl312_dada2_spe", version="7")
exact_sp <- assignSpecies(seqtab.nochim, spe_fas$path)
```

the command runs smoothly.

Maybe there is some issue with the package for the latest version?

Thank you,

Domenico

**Comment by fkeck** [comment]
Hi Domenico,

Thank you for reporting.
This is an issue we are aware of, and we will fix it as soon as possible.
In the meantime you can use version 7.

Best,
François
