### ISSUE TITLE
URL not  valid

### ISSUE THREAD

**Issue by jongarras** [fkeck/diatbarcode#5]
When running the commands indicated in the github, the following error appears:

> dbc <- get_diatbarcode(version = "last")
Error en file(file, "rt"): 
  cannot open the connection to 'http://www.francoiskeck.fr/work/diatbarcode/dic_version.csv'
Además: Aviso:
In file(file, "rt") :
  cannot open URL 'https://www.francoiskeck.fr/work/diatbarcode/dic_version.csv': HTTP status was '404 Not Found'

I have tried to find that website, but it does not exist. How could I fix this issue?

Thank you,

Jon

**Comment by fkeck** [comment]
Hi, thanks for the report. I recently migrated files to a new server and it needed some updates.
Things should work properly now.
